### ISSUE TITLE
Geospatial property type and searching

### ISSUE THREAD

**Issue by a-musing-moose** [a-musing-moose/morph#11]
MongoDB supports geospatial searching so we should too!

We need a Location or Point property type and the ability to perform geospatial searching.

Spherical geospatial searching should also be investigated

**Comment by kkamkou** [comment]
Jonathan, could you drop me any links according this feature?

**Comment by a-musing-moose** [comment]
Hey Kkamkou,

nothing has been implemented yet but the details of MongoDB's support of geo-spatial indexing can be found here: http://www.mongodb.org/display/DOCS/Geospatial+Indexing

I was thinking we need 2 things at a minimum:
- A new property type of Location (or Point)
- A new search option of $near which takes an x, y and optional distance parameter e.g. near($x, $y, $distance = null)

It would be also nice to support the $within operator if possible. something like a within(Boundry $boundry) where Boundry is a polymorphic abstract class with concrete implementations for $box, $center and $polygon.

**Comment by MiniCodeMonkey** [comment]
I worked a bit on this feature as i need it for my current project where i have to find documents that are near a specific location.

I although have to work some more on it before it is stable and broad enough to be considered for merging to the master.

I basically created a Location property and added a new function in the Storage/Object class: function findByGeoNear(Object $object, $near, $spherical = true, $maxResults = null, $maxDistance = null, $maxDistanceUnit = 'km', $query = null)

Note that this does not use the $near function but instead issues a geoNear command on the server, because the $near function didn't had all the features i needed.

One issue is tho that results are not really returned as a MangoCursor but rather as one result with the results embedded, which seems a bit "ugly". But i guess that is a Mongo issue at not really something that we should do anything about.

Suggestions for the implementation are warmly welcome.
