### ISSUE TITLE
Where I can download Morph.phar or how can I build itself using build.xml file

### ISSUE THREAD

**Issue by LarryMarthin** [a-musing-moose/morph#15]
I can't find Morph.phar.
It seems there is an error, because I found filename "Morph.phar" in .gitignore file.
Where I can download Morph.phar or how can I build itself using build.xml file?

**Comment by a-musing-moose** [comment]
Hey Larry,

As you may know I used to host morph on google code which had the ability to
store file outside of the repo.  Since moving to github I haven't come up
with a suitable alternative.

However, building it yourself is very easy and will ensure you have the
latest features.  I have added some clarifications to the installation wiki
page ( https://github.com/a-musing-moose/morph/wiki/Installation )

Let me know if you have any issues.

Regards,
Jon

**Comment by LarryMarthin** [comment]
Thanx, Jon!
I'll try to build phar, using instructions on installation page.
